"""message

Revision ID: 80c389750bdb
Revises: 2a8a0288fd16
Create Date: 2023-07-07 10:21:11.111111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c389750bdb'
down_revision = '2a8a0288fd16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurants')),
        if_not_exists=True  # Add this line to prevent table creation if it already exists
    )
    op.create_table('pizzas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_pizzas')),
        if_not_exists=True  # Add this line to prevent table creation if it already exists
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pizzas')
    op.drop_table('restaurants')
    # ### end Alembic commands ###



